mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers
from rest_framework.authtoken import views as authtoken_views
from teamBuilder import views

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'userprofiles', views.UserProfileViewSet)
router.register(r'projects', views.ProjectViewSet)
router.register(r'teams', views.TeamViewSet)
router.register(r'messages', views.MessageViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', authtoken_views.obtain_auth_token),
    url(r'^docs/', include('rest_framework_swagger.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^teambuilder/', include('teamBuilder.urls')),
]

mysite/teamBuilder/urls.py
from django.conf.urls import url

from . import views

app_name = 'teamBuilder'
urlpatterns = [
    url(r'^user/(?P<id>[0-9]+)', views.UserProfileView.as_view()),
    url(r'^team/(?P<id>[0-9]+)', views.TeamDetailView.as_view()),
    url(r'^project/create/$', views.ProjectCreateView.as_view()),
    url(r'^project/createTeam/(?P<id>[0-9]+)', views.TeamCreateView.as_view()),
    url(r'^project/manage/(?P<id>[0-9]+)', views.ProjectManageView.as_view()),
    url(r'^project/(?P<id>[0-9]+)/$', views.ProjectDetailView.as_view()),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^logout/$', views.LogoutView, name='logout'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^user/activation/(?P<activation_key>\w+)/$', views.ActivationView),
    url(r'^$', views.IndexView.as_view(), name='index')
]

mysite/teamBuilder/models.py
from __future__ import unicode_literals
import django.utils.timezone as timezone
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db.models import signals
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.conf import settings


# Create your models here.
class UserProfile(models.Model):
    owner          = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE, null=True)
    ROLE_CHOICE    = (('common', 'common'),
                      ('special', 'special'))
    realname       = models.CharField(max_length=100, blank=True, default='张三')
    phone          = models.CharField(max_length=100, blank=True, default='18800000000')
    school         = models.CharField(max_length=100, blank=True, default='Sun Yat-sen University')
    department     = models.CharField(max_length=100, blank=True, default='School of Data and Computer Science')
    major          = models.CharField(max_length=100, blank=True, default='Software Engineering')
    grade          = models.CharField(max_length=100, blank=True, default='2013')
    description    = models.TextField(blank=True, default="Enter your personal description here.")
    role           = models.CharField(max_length=20, choices=ROLE_CHOICE, blank=True, default='common')
    tags           = ArrayField(models.CharField(max_length=100), blank=True, default=['tag1', 'tag2', 'tag3'])
    activation_key = models.CharField(max_length=40, default="Not activated")

    def __str__(self):
        return (self.owner.username + "'s Profile")

def create_user_profile(sender, instance, created, **kwargs):
    """
    A hook function.
    When a user is created, its UserProfile will be created automatically.
    """
    if created:
        UserProfile.objects.create(owner=instance, role='special')

signals.post_save.connect(create_user_profile, sender=User)

@receiver(signals.post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

class Project(models.Model):
    """
    The project's title is unique.
    """
    owner          = models.ForeignKey(UserProfile, related_name='project_published', on_delete=models.CASCADE, null=True)
    title          = models.CharField(max_length=100, blank=True, unique=True, default='Demo Project')
    description    = models.TextField(blank=True, default="Enter your description here")
    school         = ArrayField(models.CharField(max_length=200), blank=True, default=['Sun Yat-sen University', 'South China University of Technology'])
    department     = ArrayField(models.CharField(max_length=200), blank=True, default=['School of Data and Computer Science', 'School of Engineering'])
    major          = ArrayField(models.CharField(max_length=200), blank=True, default=['Software Engineering', 'Computer Science and Technology'])
    deadline       = models.DateTimeField('deadline', default=timezone.now, blank=True)
    min_num        = models.PositiveIntegerField(blank=True, default=3)
    max_num        = models.PositiveIntegerField(blank=True, default=10)

    def __str__(self):
        return self.title

class Team(models.Model):
    owner          = models.ForeignKey(UserProfile, related_name='team_captain', on_delete=models.CASCADE, null=True)
    project        = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='team_enrolled')
    name           = models.CharField(max_length=100, blank=True, unique=True, default='Demo Team')
    tags           = ArrayField(models.CharField(max_length=100), blank=True, null=True, default=['tag1', 'tag2', 'tag3'])
    description    = models.TextField(default="Enter your description here")
    is_confirmed   = models.BooleanField(default=False)
    is_special     = models.BooleanField(default=False)
    member_list    = models.ManyToManyField(UserProfile, related_name='team_member', blank=True)
    candidate_list = models.ManyToManyField(UserProfile, related_name='team_candidate', blank=True)

    def __str__(self):
        return self.name

class Message(models.Model):
    """
    Define all kind of communication between users.
    Owner is receiver.
    """
    MSG_CHOICE = (
        ('COMMENT', 'Comment'),
        ('APPLY', 'Apply'),
    )
    owner     = models.ForeignKey(UserProfile, related_name='msg_received', on_delete=models.CASCADE, null=True)
    msg_type  = models.CharField(max_length=30, choices=MSG_CHOICE, default=(MSG_CHOICE[0]))
    content   = models.TextField(max_length=300, default="Enter your message here")
    post_time = models.DateTimeField('publish_time', default=timezone.now, null=True)
    sender    = models.ForeignKey(UserProfile, related_name='msg_sent', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return (self.owner.realname + " " + self.msg_type + " " + self.content + " " + str(self.post_time))

mysite/teamBuilder/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

class PublishProjectForm(forms.Form):
    pass

class CreateTeamForm(forms.Form):
    pass

class RegisterForm(forms.Form):
    username = forms.CharField(
        label=u'昵称',
        help_text=u'昵称可用于登录，不能包含空格和@字符。',
        max_length=20,
        initial='',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    email = forms.EmailField(
        label=u'邮箱',
        help_text=u'邮箱可用于登录，最重要的是需要邮箱来找回密码，所以请输入您的可用邮箱。',
        max_length=50,
        initial='',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    password = forms.CharField(
        label=u'密码',
        help_text=u'密码只有长度要求，长度为 8 ~ 20 。',
        min_length=8,
        max_length=20,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    confirm_password = forms.CharField(
        label=u'确认密码',
        min_length=8,
        max_length=20,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        if ' ' in username or '@' in username:
            raise forms.ValidationError(u'昵称中不能包含空格和@字符')
        res = User.objects.filter(username=username)
        if len(res) != 0:
            raise forms.ValidationError(u'此昵称已经注册，请重新输入')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        res = User.objects.filter(email=email)
        if len(res) != 0:
            raise forms.ValidationError(u'此邮箱已经注册，请重新输入')
        return email

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password and confirm_password:
            if password != confirm_password:
                raise forms.ValidationError(u'两次密码输入不一致，请重新输入')

    def save(self):
        username = self.cleaned_data['username']
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        user = User.objects.create_user(username, email, password, is_active=False)
        user.save()

class LoginForm(forms.Form):
    username = forms.CharField(
        label='Username',
        max_length=20,
        initial='',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(
        label='Password',
        min_length=8,
        max_length=20,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if user is None:
                raise forms.ValidationError('Username and Password doesn\'t matched')
            else:
                if not user.is_active:
                    raise forms.ValidationError('This account is not activated yet!')

mysite/teamBuilder/views.py
from django.http import HttpResponseRedirect
from django.views import generic
from django.core.urlresolvers import reverse, reverse_lazy
from django.core.mail import send_mail, BadHeaderError, EmailMultiAlternatives
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render
from django.conf import settings
from django.utils import timezone
from rest_framework import viewsets, filters
from rest_framework.permissions import *
from .serializers import *
from .permissions import *
from .models import *
from .forms import *
import datetime
import hashlib
import random
import re

# Create your views here.

class UserProfileView(generic.TemplateView):
	template_name = 'teamBuilder/accounts/profile.html'

class TeamDetailView(generic.TemplateView):
	template_name = 'teamBuilder/team/team_detail.html'

class ProjectCreateView(generic.TemplateView):
	template_name = 'teamBuilder/project/create_project.html'

class TeamCreateView(generic.TemplateView):
	template_name = 'teamBuilder/team/create_team.html'

class ProjectManageView(generic.TemplateView):
	template_name = 'teamBuilder/project/manage_project.html'

class ProjectDetailView(generic.TemplateView):
	template_name = 'teamBuilder/project/project_detail.html'

class IndexView(generic.TemplateView):
    template_name = 'teamBuilder/index.html'

class RegisterView(generic.edit.FormView):
    template_name = 'teamBuilder/accounts/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('teamBuilder:index')

    def mail_validate(self, username, to_email):
        subject = u'Teambuilder用户验证'
        from_email = 'teambuilder@sina.com'
        # generate activation code
        salt = hashlib.sha1(str(random.random()).encode('utf-8')).hexdigest()[:5]
        username = username.encode('utf-8')
        code = salt.encode('utf-8') + username
        activation_key = hashlib.sha1(code).hexdigest()
        user = User.objects.get(username=username)
        profile = user.user_profile
        profile.activation_key = activation_key
        profile.save()

        text_content = u'<p>您好，' + username.decode('utf-8') + u'！恭喜您注册成功，请点击下面的链接激活您的账户：</p>'
        activation_url = self.request.get_host() + '/teambuilder/user/activation/' + activation_key
        html_content = text_content + u'<b>激活链接：</b><a href="'+ activation_url +'">' + activation_url + '</a>'
        send_mail(subject, '', from_email, [to_email], html_message=html_content)

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        user = form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        email = form.cleaned_data.get('email')
        RegisterView.mail_validate(self, username, email)
        user = authenticate(username=username, password=password)
        login(self.request, user)
        # return super(RegisterView, self).form_valid(form)
        context = {
            'err_msg': '注册成功，请通过您的邮箱收到的验证邮件激活您的账号'
        }
        return render(self.request, 'teamBuilder/activation/msg.html', context)

def ActivationView(request, activation_key):
    SHA_RE = re.compile('^[a-f0-9]{40}$')
    if SHA_RE.search(activation_key):
        try:
            user_profile = UserProfile.objects.get(activation_key=activation_key)
        except :
            context = {
                'err_msg': '无效的验证地址'
            }
            return render(request, 'teamBuilder/activation/msg.html', context)
        user = user_profile.owner

        # check time expired
        expiration_date = datetime.timedelta(seconds=settings.EXPIRATION_TIME_DELTA)
        if (user.date_joined + expiration_date <= timezone.now()):
            context = {
                'err_msg': '该验证地址已过期，请重新注册'
            }
            user.delete()
            return render(request, 'teambuilder/activation/msg.html', context)
        else:
            user.is_active = True
            user.save()
            user_profile.activation_key = u'ALREADY_ACTIVATED'
            user_profile.save()
            # return HttpResponseRedirect(reverse('teamBuilder:login'))
            context = {
                'msg': '验证成功，5秒后跳转到登录页面'
            }
            return render(request, 'teambuilder/activation/success.html', context)
    else:
        context = {
            'err_msg': '错误的验证地址'
        }
        return render(request, 'teamBuilder/activation/msg.html', context)

class LoginView(generic.edit.FormView):
    template_name = 'teamBuilder/accounts/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('teamBuilder:index')

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        print(self.request.get_host())
        return super(LoginView, self).form_valid(form)

def LogoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('teamBuilder:index'))

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = (IsUserOrReadOnly, )

    def get_object(self):
        pk = self.kwargs.get('pk')

        if pk == "current":
            return self.request.user

        return super(UserViewSet, self).get_object()


class UserProfileViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users' profile to be viewed or edited
    """
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly, )


class ProjectViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows projects to be viewed or edited
    """
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ('title',)
    permission_classes = [IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly,
                          IsPublisherOrReadOnly,
                          ]

    def perform_create(self, serializer):
        user_profile = UserProfile.objects.filter(owner=self.request.user)[0]
        serializer.save(owner=user_profile)

class TeamViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows teams to be viewed or edited
    """
    queryset = Team.objects.all()
    serializer_class = TeamSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def perform_create(self, serializer):
        user_profile = UserProfile.objects.filter(owner=self.request.user)
        serializer.save(owner=user_profile[0], member_list=user_profile)

class MessageViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows comments to be viewed or edited
    """
    queryset = Message.objects.all()
    serializer_class = MessageSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly, )

    def perform_create(self, serializer):
        user_profile = UserProfile.objects.filter(owner=self.request.user)[0]
        serializer.save(owner=user_profile)

mysite/teamBuilder/templates/teamBuilder/accounts/login.html
{% extends "index.html" %}

{% block content %}
<!-- <div class="col-md-7">
    <img src="/static/teamBuilder/images/login-align.jpeg" class="img-thumbnail" alt="for-align" />
</div>
<div class="col-md-5">
  <form action="{% url 'teamBuilder:login' %}" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Submit" class="btn btn-default">登录</button>
  </form>
</div> -->
    <div>
      <div class="col-md-7">
          <img src="/static/teamBuilder/images/login-align.jpeg" class="img-thumbnail" alt="for-align" />
      </div>
      <div class="col-md-5">
          <form class="form-horizontal" action="/api-token-auth/" name="login-form">
            <div class="form-group">
              <label for="inputUsername3" class="col-sm-2 control-label">Username</label>
              <div class="col-sm-10">
                <input class="form-control" id="inputUsername3" name="username" placeholder="Username">
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
              <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword3" name="password" placeholder="Password">
              </div>
            </div>
<!--             <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Remember me
                  </label>
                </div>
              </div>
            </div> -->
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary" id="sign-in">Sign in</button>
              </div>
            </div>
          </form>
      </div>
    </div>
    <script type="text/javascript" src="/static/teamBuilder/js/login.js"></script>
{% endblock %}

mysite/teamBuilder/templates/teamBuilder/accounts/profile.html
{% extends "index.html" %}

{% block content %}
    <div class="container" id="profile_outer">
        <img src="/static/teamBuilder/images/touxiang.jpg" alt="avator" style="width:100px; height:100px;"/>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">personal infomation</h3>
          </div>
          <div class="panel-body">
            <p>
                username: <span id="username" class="info" style="cursor:pointer;"></span>
                <input type="text" class="form-control" placeholder="username" style="display:none;">
                <button type="button" class="btn btn-primary update-button" style="margin-top: 8px; display:none;">更新</button>
            <p>
            <p>
                email: <span id="email" class="info" style="cursor:pointer;"></span>
                <input type="text" class="form-control" placeholder="email" style="display:none;">
                <button type="button" class="btn btn-primary update-button" style="margin-top: 8px; display:none;">更新</button>
            <p>
            <p>
                realname: <span id="realname" class="info" style="cursor:pointer;"></span>
                <input type="text" class="form-control" placeholder="realname" style="display:none;">
                <button type="button" class="btn btn-primary update-button" style="margin-top: 8px; display:none;">更新</button>
            <p>
            <p>
                phone: <span id="phone" class="info" style="cursor:pointer;"></span>
                <input type="text" class="form-control" placeholder="phone" style="display:none;">
                <button type="button" class="btn btn-primary update-button" style="margin-top: 8px; display:none;">更新</button>
            <p>
            <p>
                school: <span id="school" class="info" style="cursor:pointer;"></span>
                <input type="text" class="form-control" placeholder="school" style="display:none;">
                <button type="button" class="btn btn-primary update-button" style="margin-top: 8px; display:none;">更新</button>
            <p>
            <p>
                department: <span id="department" class="info" style="cursor:pointer;"></span>
                <input type="text" class="form-control" placeholder="department" style="display:none;">
                <button type="button" class="btn btn-primary update-button" style="margin-top: 8px; display:none;">更新</button>
            <p>
            <p>
                major: <span id="major" class="info" style="cursor:pointer;"></span>
                <input type="text" class="form-control" placeholder="major" style="display:none;">
                <button type="button" class="btn btn-primary update-button" style="margin-top: 8px; display:none;">更新</button>
            <p>
            <p>
                grade: <span id="grade" class="info" style="cursor:pointer;"></span>
                <input type="text" class="form-control" placeholder="grade" style="display:none;">
                <button type="button" class="btn btn-primary update-button" style="margin-top: 8px; display:none;">更新</button>
            <p>
            <p>
                description: <span id="description" class="info" style="cursor:pointer;"></span>
                <input type="text" class="form-control" placeholder="description" style="display:none;">
                <button type="button" class="btn btn-primary update-button" style="margin-top: 8px; display:none;">更新</button>
            <p>
          </div>
        </div>
        <div id="teams">
<!--             <a class="btn btn-default" href="#" role="button">队伍1</a>
            <a class="btn btn-default" href="#" role="button">队伍2</a>
            <a class="btn btn-default" href="#" role="button">队伍3</a>
            <a class="btn btn-default" href="#" role="button">队伍4</a> -->
        </div>
        <div class="personal_info_comment panel panel-default" style="margin-top: 10px;">
<!--             <div class="panel-body">
                <img src="/static/images/touxiang.jpg" alt="avator" style="width:55px;height:55px;display:inline-block;"/>
                <div style="display:inline-block">
                    <p>
                        <span class="personal_info_comment_time">2016-7-7 12:22:22</span>
                        </br>
                        <span class="personal_info_comment_owner">owner</span>
                        <span>:</span>
                        <span class="personal_info_comment_content">content</span>
                    </p>
                </div>
            </div> -->
        </div>
    </div>
    <script type="text/javascript" src="/static/teamBuilder/js/profile.js"></script>
{% endblock %}

mysite/teamBuilder/templates/teamBuilder/accounts/register.html
{% extends "index.html" %}

{% block content %}
<div class="col-md-3"></div>
<div class="col-md-6 ">

  <form action="{% url 'teamBuilder:register' %}" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Submit" class="btn btn-default">注册</button>
  </form>

<!--     <form class="form-horizontal">
      <div class="form-group">
        <label for="inputUsername3" class="col-sm-2 control-label">Username</label>
        <div class="col-sm-10">
          <input type="username" class="form-control" id="inputusername3" placeholder="Username">
        </div>
      </div>

      <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
          <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
        </div>
      </div>

      <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
        </div>
      </div>

      <div class="form-group">
        <label for="inputPasswordAgain3" class="col-sm-2 control-label">Password Again</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" id="inputPasswordAgain3" placeholder="Password Again">
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Sign up</button>
        </div>
      </div>
    </form> -->
</div>
<div class="col-md-3"></div>
{% endblock %}